version: '3'

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "30005:9000"
      - "30006:9001"
    volumes:
      - E:/beshe/yinzhang/ultralytics/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=11_minio
    command: server /data --console-address ":9001"
