version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=11
      - POSTGRES_PASSWORD=11_postgres
    ports:
      - "5432:5432"
    volumes:
      - E:/beshe/yinzhang/ultralytics/pg/data:/var/lib/postgresql/data
